version: "3"

services:
    php-env:
      depends_on:
        - longrich_db
      build: .
      volumes:
        - ./longrich:/var/www/html
#        - ./apache-config/apache2.conf:/etc/apache2/apache2.conf
        - /etc/apache2/sites-available/000-default.conf:/etc/apache2/custom-conf.conf
      ports:
        - "8080:80"



    longrich_db:
      image: mysql:latest
      restart: always
      volumes:
        - longrich_db_data:/var/lib/mysql
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: \@Dm1n1Str\@t3urDC


    phpmyadmin:
      image: phpmyadmin:latest
      depends_on:
        - longrich_db
      restart: always
      ports:
        - "9002:80"
      environment:
        #- PMA_ARBITRARY=1
        PMA_HOST: 'longrich_db'
        #- MYSQL_USER: root
        #- MYSQL_PASSWORD: \@Dm1n1Str\@t3urDC

volumes:
  longrich_db_data: {}